# @package _global_

defaults:
  - override /data: depth

name: monodepth

pi3:
  #pretrained_model_name_or_path: /mnt/extdisk1/wanghaoxuan/SVD-pi3/Pi3_main/pi3_model.safetensors
  #pretrained_model_name_or_path: /data/wanghaoxuan/SVD_Pi3_cache/Pi3_whitening_only_0.8.safetensors
  #pretrained_model_name_or_path: /data/wanghaoxuan/SVD_Pi3_cache/Pi3_whitening_only_0.8_1024.safetensors
  #pretrained_model_name_or_path: /data/wanghaoxuan/SVD_Pi3_cache/Pi3_whitening_only_0.8_qkv_only.safetensors
  #pretrained_model_name_or_path: /data/wanghaoxuan/SVD_Pi3_cache/Pi3_whitening_only_0.8_proj_only.safetensors
  #pretrained_model_name_or_path: /data/wanghaoxuan/SVD_Pi3_cache/Pi3_whitening_only_0.8_fc_only.safetensors
  #pretrained_model_name_or_path: /data/wanghaoxuan/SVD_Pi3_cache/Pi3_whitening_only_0.9.safetensors
  #pretrained_model_name_or_path: /data/wanghaoxuan/SVD_Pi3_cache/Pi3_lora_V_0.8.safetensors
  #pretrained_model_name_or_path: /data/wanghaoxuan/SVD_Pi3_cache/Pi3_lora_U_0.8.safetensors
  #pretrained_model_name_or_path: /data/wanghaoxuan/SVD_Pi3_cache/LoRA/Pi3_lora_U_0.8.safetensors
  #pretrained_model_name_or_path: /data/wanghaoxuan/SVD_Pi3_cache/Pi3_whitening_only_0.8_FINAL_CLEAN.safetensors
  #pretrained_model_name_or_path: /data/wanghaoxuan/SVD_Pi3_cache/Pi3_whitening_only_0.8_FINAL.safetensors
  #pretrained_model_name_or_path: /data/wanghaoxuan/SVD_Pi3_cache/Pi3_whitening_only_0.8_ALL_IN.safetensors
  pretrained_model_name_or_path: /data/wanghaoxuan/SVD_Pi3_cache/Pi3_whitening_only_0.8_debug.safetensors

eval_datasets:
  - sintel
  # - bonn
  # - kitti
  # - nyu-v2

invariant: median-scale  # using median(gt) / median(pred) as scale factor

overwrite: False
no_crop: True
load_img_size: 512

device: cuda

verbose: False
save_suffix: null