# @package _global_

defaults:
  - override /data: relpose-angular

name: relpose-angular

pi3:
  pretrained_model_name_or_path: /data/wanghaoxuan/SVD_Pi3_cache/model.safetensors
  #pretrained_model_name_or_path: /data/wanghaoxuan/SVD_Pi3_cache/Pi3_svd_baseline_0.8.safetensors
  #pretrained_model_name_or_path: /data/wanghaoxuan/SVD_Pi3_cache/Pi3_svd_baseline_0.5.safetensors
  #pretrained_model_name_or_path: /data/wanghaoxuan/SVD_Pi3_cache/Pi3_svd_baseline_0.3.safetensors
  #pretrained_model_name_or_path: /data/wanghaoxuan/SVD_Pi3_cache/Pi3_svd_baseline_0.2.safetensors


eval_datasets:
  # - Re10K
  - CO3Dv2

no_crop: False
load_img_size: 512

device: cuda

verbose: False

seed: 42

save_suffix: null
