# @package _global_

defaults:
  - override /data: relpose-distance

name: relpose-distance

pi3:
  #pretrained_model_name_or_path: /data/wanghaoxuan/SVD_Pi3_cache/model.safetensors
  #pretrained_model_name_or_path: /data/wanghaoxuan/SVD_Pi3_cache/Pi3_svd_baseline_0.8.safetensors
  #pretrained_model_name_or_path: /data/wanghaoxuan/SVD_Pi3_cache/Pi3_svd_baseline_0.5.safetensors
  #pretrained_model_name_or_path: /data/wanghaoxuan/SVD_Pi3_cache/Pi3_svd_baseline_0.3.safetensors
  #pretrained_model_name_or_path: /data/wanghaoxuan/SVD_Pi3_cache/Pi3_svd_baseline_0.2.safetensors

  #pretrained_model_name_or_path: /data/wanghaoxuan/SVD_Pi3_cache/Pi3_whitening_only_scannet_0.2.safetensors

  #pretrained_model_name_or_path: /data/wanghaoxuan/SVD_Pi3_cache/Pi3_whitening_only_scannet_0.4_BASE.safetensors
  
  # pretrained_model_name_or_path: /data/wanghaoxuan/yusen_stuff/SVD_Pi3_cache/Pi3_whitening_only_scannet_0.4_BASE.safetensors

  
  # pretrained_model_name_or_path: vggt
  pretrained_model_name_or_path: /data/wanghaoxuan/yusen_stuff/SVD_Pi3_cache/VGGT_svd_baseline_0.2.safetensors




eval_datasets:
  # - sintel
  # - tum
  - scannetv2

no_crop: False
load_img_size: 512
pose_eval_stride: 1

device: cuda

verbose: False

seed: 42

save_suffix: null